In [3]:
# 6/6/2018 - Exercise #1
import numpy as np

# Create evenly spaced values of type np.int32 within the interval (1, 20, 1)
a = np.arange(1, 20, 1, dtype=np.int32)
print(a)


def myfunc(start, end, step):
    while start <= end:
        yield start
        start += step
        
for x in myfunc(a[0], a[len(a)-1], 0.2):
    if x > 12 and x < 14:
        print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
12.2
12.4
12.6
12.8
13.0
13.2
13.4
13.6
13.8
14.0


In [17]:
# 6/6/2018 - Exercise #2 - Attempt
import numpy as np

my_array = np.linspace(5, 45, 6)
my_array.tofile('exercise2.txt')

class _FileOperations():
    def write_my_file(array):
        file = open('exercise2.txt', 'r+')
        read_array = file.readlines()
        
        np_array = np.array(read_array[0], dtype=np.int16)
        matrix = np.matrix([[1], [2], [3]])
        product = np_array * matrix
        
        file.write(product)
        file.close()
    
    def read_my_file():
        file = open('exercise2.txt', 'r')
        lines = file.readlines()
        print(lines[0])
        file.close()

file_operations = _FileOperations()
file_operations.write_my_file()
file_operations.read_my_file()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 37: invalid start byte

In [4]:
# 6/6/2018 - Exercise #2 - Solution
class _file_operations():
    def write_my_file(A):
        file = open('exericse2', 'w')
        file.write(str(A))
        file.close()
        
    def read_my_file():
        file = open('exercise2', 'r')
        B = file.read()
        file.close()
        return B

B = np.random.randint(5, 45, 6)
B.tofile('exercise2', sep=',', format='%s')
B = _file_operations.read_my_file()
B = np.array(B.split(','), dtype=np.int16)
C = np.matrix([[3], [2], [5]])
D = C*B
_file_operations.write_my_file(D)
print(_file_operations.read_my_file())

16,25,18,30,6,37


In [52]:
# 6/9/2018 - Homework #2
import numpy as np

# Create matrix A with size (3,5) containing random numbers
A = np.matrix(np.random.random((3,5)))
print('Create matrix A with size (3,5) containing random numbers:')
print(A)
print('\n')

# Find the size and length of A
A_size = A.size
A_length = len(A)
print('Find the size and length of A:')
print("Size of A: {}".format(A_size))
print("Length of A: {}".format(A_length))
print('\n')

# Resize (crop/slice) matrix A to size (3,4)
A = np.resize(A, (3,4))
print('Resize (crop/slice) matrix A to size (3,4):')
print(A)
print('\n')

# Find the transpose of matrix A and assign it to B
B = A.T
print('Find the transpose of matrix A and assign it to B:')
print(B)
print('\n')

# Find the minimum value in column 1 of matrix B
B_min = min(B[:, 1])
print('Find the minimum value in column 1 of matrix B:')
print(B_min)
print('\n')

# Find the minimum and maximum values for the entire matrix A
A_min = A.min()
A_max = A.max()
print('Find the minimum and maximum values for the entire matrix A:')
print("Maximum of A: {}".format(A_max))
print("Minimum of A: {}".format(A_min))
print('\n')

# Create vector X (an array) with 4 random numbers
X = np.random.random(4)
print('Create vector X (an array) with 4 random numbers:')
print(X)
print('\n')

# Create a function and pass vector X and matrix A in it
# In the new function multiply vector X with matrix A and assign the result to D
def my_function(vector_x, vector_a):
    D = X*A
    print('Create a function and pass vector X and matrix A in it')
    print('In the new function multiply vector X with matrix A and assign the result to D')
    print("D:")
    print(D)
    print('\n')
    return D

D = my_function(X, A)

# Create a complex number Z with absolute and real parts != 0
Z = np.complex(1,3)
print('Create a complex number Z with absolute and real parts != 0:')
print("Z: {}".format(Z))
print('\n')

# Show its real and imaginary parts as well as its absolute value
print('Show its real and imaginary parts as well as its absolute value:')
print("Z real: {}".format(Z.real))
print("Z imaginary: {}".format(Z.imag))
print("Z absolute: {}".format(np.absolute(Z)))
print('\n')

# Multiply result D with the absolute value of Z and record it to C
C = D * np.absolute(Z)
print('Multiply result D with the absolute value of Z and record it to C:')
print(C)
print('\n')

# Convert matrix B from a matrix to a string and overwrite B
B = str(B)
print('Convert matrix B from a matrix to a string and overwrite B:')
print(B)
print("Type of B: {}".format(type(B)))
print('\n')

# Display a text on the screen: '<Your Name> is done with HW2'
name = 'David Cheng'
print('Display a text on the screen: \'<Your Name> is done with HW2\'')
print("{} is done with HW2".format(name))

Create matrix A with size (3,5) containing random numbers:
[[ 0.39805232  0.95550467  0.02689394  0.39771486  0.51814313]
 [ 0.57007321  0.56746533  0.76357853  0.83110627  0.94611009]
 [ 0.12381008  0.70673607  0.79145349  0.71533455  0.46372345]]


Find the size and length of A:
Size of A: 15
Length of A: 3


Resize (crop/slice) matrix A to size (3,4):
[[ 0.39805232  0.95550467  0.02689394  0.39771486]
 [ 0.51814313  0.57007321  0.56746533  0.76357853]
 [ 0.83110627  0.94611009  0.12381008  0.70673607]]


Find the transpose of matrix A and assign it to B:
[[ 0.39805232  0.51814313  0.83110627]
 [ 0.95550467  0.57007321  0.94611009]
 [ 0.02689394  0.56746533  0.12381008]
 [ 0.39771486  0.76357853  0.70673607]]


Find the minimum value in column 1 of matrix B:
0.518143127774


Find the minimum and maximum values for the entire matrix A:
Maximum of A: 0.9555046651024238
Minimum of A: 0.026893942789675385


Create vector X (an array) with 4 random numbers:
[ 0.070796    0.76910281  0.958