In [22]:
import numpy as np
import scipy
import matplotlib

In [12]:
a = 128
print(id(a))
b = a
print(id(b))


a = 5
print(b)
print(id(a))
print(id(b))

a = 128
print(id(a))

4435884000
4435884000
128
4435880064
4435884000
4435884000


In [1]:
some_string = 'abcdefghijklmnop'
character = 'a'
print(ord(character)) # ord() returns an integer representing the Unicode code point of the character when the argument is a unicode object, or the value of the byte when the argument is an 8-bit string.

97


In [13]:
# 6/6/2018 - Exercise #1
import numpy as np

# Create evenly spaced values of type np.int32 within the interval (1, 20, 1)
a = np.arange(1, 20, 1, dtype=np.int32)
print(a)


def myfunc(start, end, step):
    while start <= end:
        yield start
        start += step
        
for x in myfunc(a[0], a[len(a)-1], 0.2):
    if x > 12 and x < 14:
        print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
12.2
12.4
12.6
12.8
13.0
13.2
13.4
13.6
13.8
14.0


In [19]:
a = np.array([[2, 4, 6], [2, 23, 6], [64, 23, 55]], dtype=np.int16)
print(a)
print(a.size)
print(a.shape)
print(type(a))
print(a[2, 2]) # this is how we index a particular element in the array

b = a[0,:]
print(b)
print(b.shape)

b[2] = 88
print(b[2]) # => since b is a view of a (the base), this change will be reflected in a as well
print(a[0,2]) # => should be 88

print(a)
print(b)


[[ 2  4  6]
 [ 2 23  6]
 [64 23 55]]
9
(3, 3)
<class 'numpy.ndarray'>
55
[2 4 6]
(3,)
88
88
[[ 2  4 88]
 [ 2 23  6]
 [64 23 55]]
[ 2  4 88]


In [20]:
c = np.zeros(shape=(4,5)) # contains zeros for all elements
print(c)

d = np.empty(shape=(2,2)) # contains meaningless data
print(d)

e = np.ndarray(shape=(2,3), dtype=complex, offset=np.float_().itemsize, order='C')
print(e)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ -2.00000000e+000   1.49457098e-154]
 [ -2.00000000e+000   2.82464293e-309]]
[[ -2.00000000e+000 -2.00000000e+000j   2.96439388e-323 +0.00000000e+000j
    0.00000000e+000 +0.00000000e+000j]
 [ -2.00000000e+000 -2.00000000e+000j   1.48219694e-323 +0.00000000e+000j
    0.00000000e+000 +8.34402697e-309j]]


In [25]:
a = np.linspace(1, 5, 10) # create an array of 10 values between the range of 1-5
print(a)

a = np.linspace(1, 5, 10, endpoint=False) # 5 will not be included in the array, since endpoint=False
print(a)

a = np.linspace(1, 5, 10, endpoint=True)
print(a)

[ 1.          1.44444444  1.88888889  2.33333333  2.77777778  3.22222222
  3.66666667  4.11111111  4.55555556  5.        ]
[ 1.   1.4  1.8  2.2  2.6  3.   3.4  3.8  4.2  4.6]
[ 1.          1.44444444  1.88888889  2.33333333  2.77777778  3.22222222
  3.66666667  4.11111111  4.55555556  5.        ]


In [37]:
f = np.ndarray(shape=(2,3,2), dtype=complex)
print('f')
print(f)
print('---------------')
print('f.real')
print(f.real)
print('---------------')
print('f.real.T') # T means transpose
print(f.real.T)
print('---------------')
print('f.imag.flags')
print(f.flags)
print('We can also change these flags, for example can we lock this object to be non writeable?')
f.flags.writeable = False
print(f.flags)
print('---------------')
print('f.imag.data')
print(f.imag.data)
print('---------------')
print('f.dtype')
print(f.dtype)
print('---------------')
print('f.shape')
print(f.shape)
print('---------------')
print('f.T.shape')
print(f.T.shape)
print('---------------')
print('f.size')
print(f.size)
print('---------------')
print('f.nbytes')
print(f.nbytes)
print('---------------')
print('f.ndim')
print(f.ndim)

f
[[[ -2.00000000e+000 +1.73059496e-77j   6.42285340e-323 +0.00000000e+00j]
  [  0.00000000e+000 +0.00000000e+00j   0.00000000e+000 +0.00000000e+00j]
  [  0.00000000e+000 +0.00000000e+00j   0.00000000e+000 +0.00000000e+00j]]

 [[  0.00000000e+000 +0.00000000e+00j   0.00000000e+000 +0.00000000e+00j]
  [  0.00000000e+000 +0.00000000e+00j   0.00000000e+000 +0.00000000e+00j]
  [  0.00000000e+000 +0.00000000e+00j   0.00000000e+000 +0.00000000e+00j]]]
---------------
f.real
[[[ -2.00000000e+000   6.42285340e-323]
  [  0.00000000e+000   0.00000000e+000]
  [  0.00000000e+000   0.00000000e+000]]

 [[  0.00000000e+000   0.00000000e+000]
  [  0.00000000e+000   0.00000000e+000]
  [  0.00000000e+000   0.00000000e+000]]]
---------------
f.real.T
[[[ -2.00000000e+000   0.00000000e+000]
  [  0.00000000e+000   0.00000000e+000]
  [  0.00000000e+000   0.00000000e+000]]

 [[  6.42285340e-323   0.00000000e+000]
  [  0.00000000e+000   0.00000000e+000]
  [  0.00000000e+000   0.00000000e+000]]]
--------------

In [43]:
# Flat vs Flatten
g = np.arange(12, 24).reshape(3,4)
print(g)
print(g[:, :])
print(g.T)

print('flat')
print(g.flat[6])
print(g.flat[9])
print(g.flat[:])

print('flatten')
print(g.flatten())

print(g.T.flat[6])

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 16 20]
 [13 17 21]
 [14 18 22]
 [15 19 23]]
flat
18
21
[12 13 14 15 16 17 18 19 20 21 22 23]
flatten
[12 13 14 15 16 17 18 19 20 21 22 23]
14


In [44]:
j = np.array([[12, 34, 66, 23], [5, 5, 11, 23], [23, 86, 12, 44]])
print(j)
print(j.ctypes)
print(j.ctypes.data)
print(j.ctypes.shape._length_)
print(j.ctypes.strides._length_)
print(j.ctypes.shape._type_)

[[12 34 66 23]
 [ 5  5 11 23]
 [23 86 12 44]]
140226232681024
2
2
<class 'ctypes.c_long'>


In [45]:
k = np.array([0, 1, 2, 3, 4])
print(k.base is None)

l = k[0:2]
print(l.base is k)

True
True


In [53]:
a = np.array([2,3])
print(a*a)

m = np.matrix([2,3])
# print(m*m) # This does not work, since it is a matrix!
print(m*m.T)

c = np.ndarray([2,3], dtype=np.int16)
print(c*c)

# To get the matrix multiplication of an ndarray
print(np.dot(a, a.T))
print(np.dot(c, c.T))

[4 9]
[[13]]
[[0 0 0]
 [0 0 0]]
13
[[0 0]
 [0 0]]


In [55]:
help(np.ndarray.tofile)

Help on method_descriptor:

tofile(...)
    a.tofile(fid, sep="", format="%s")
    
    Write array to a file as text or binary (default).
    
    Data is always written in 'C' order, independent of the order of `a`.
    The data produced by this method can be recovered using the function
    fromfile().
    
    Parameters
    ----------
    fid : file or str
        An open file object, or a string containing a filename.
    sep : str
        Separator between array items for text output.
        If "" (empty), a binary file is written, equivalent to
        ``file.write(a.tobytes())``.
    format : str
        Format string for text file output.
        Each entry in the array is formatted to text by first converting
        it to the closest Python type, and then using "format" % item.
    
    Notes
    -----
    This is a convenience function for quick storage of array data.
    Information on endianness and precision is lost, so this method is not a
    good choice for files in